<?php

return [
  'name' => 'sleek',
  'author' => 'contact@26bz.online',
  'url' => 'https://26bz.online/',

  'settings' => [
    [
      'name' => 'direct_checkout',
      'label' => 'Direct Checkout',
      'type' => 'checkbox',
      'default' => false,
      'database_type' => 'boolean',
      'description' => 'Don\'t show the product overview page, go directly to the checkout page',
    ],
    [
      'name' => 'small_images',
      'label' => 'Small Images',
      'type' => 'checkbox',
      'default' => false,
      'database_type' => 'boolean',
      'description' => 'Show small images in the product overview page',
    ],
    [
      'name' => 'show_category_description',
      'label' => 'Show Category Description',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Show the category description in the product overview page/homepage',
    ],

    [
      'name' => 'force_dark_mode',
      'label' => 'Force Dark Mode',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Force dark mode for all users (disables theme toggle)',
    ],
    [
      'name' => 'enable_features_section',
      'label' => 'Enable Features Section',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Show the features section on the homepage',
    ],
    [
      'name' => 'enable_panel_showcase',
      'label' => 'Enable Panel Showcase',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Show the game panel showcase section on the homepage',
    ],
    [
      'name' => 'enable_cta_section',
      'label' => 'Enable CTA Section',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Show the call-to-action section on the homepage',
    ],
    [
      'name' => 'enable_logo_marquee',
      'label' => 'Enable Logo Marquee',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Show the logo marquee section on the homepage',
    ],

    [
      'name' => 'home_page_text',
      'label' => 'Hero Title Text',
      'type' => 'markdown',
      'default' => 'Professional **Web Hosting** Made Simple',
      'description' => 'Main headline for the hero section. Use **bold** for emphasis.',
    ],
    [
      'name' => 'hero_description',
      'label' => 'Hero Description Text (Hero only)',
      'type' => 'textarea',
      'default' => 'Reliable, fast, and secure hosting solutions for businesses of all sizes. Get started in minutes with our easy-to-use platform.',
      'description' => 'Paragraph text displayed beneath the hero title. Footer description is managed separately below.',
    ],
    [
      'name' => 'hero_primary_button_text',
      'label' => 'Hero Primary Button Text',
      'type' => 'text',
      'default' => '',
      'description' => 'Text for the primary hero button. Leave empty to hide the button.',
    ],
    [
      'name' => 'hero_primary_button_url',
      'label' => 'Hero Primary Button URL',
      'type' => 'text',
      'default' => '#services',
      'description' => 'URL or anchor for the primary hero button (e.g., #services, /products, https://example.com)',
    ],
    [
      'name' => 'hero_secondary_button_text',
      'label' => 'Hero Secondary Button Text',
      'type' => 'text',
      'default' => '',
      'description' => 'Text for the secondary hero button. Leave empty to hide the button.',
    ],
    [
      'name' => 'hero_secondary_button_url',
      'label' => 'Hero Secondary Button URL',
      'type' => 'text',
      'default' => '/tickets/create',
      'description' => 'URL or route for the secondary hero button (e.g., /contact, /tickets/create)',
    ],

    [
      'name' => 'features_title',
      'label' => 'Features Section Title',
      'type' => 'text',
      'default' => 'Why Choose Our Hosting?',
      'description' => 'Main title for the features section',
    ],
    [
      'name' => 'features_subtitle',
      'label' => 'Features Section Subtitle',
      'type' => 'text',
      'default' => 'We provide everything you need to succeed online with reliable, fast, and secure hosting solutions.',
      'description' => 'Subtitle text for the features section',
    ],
    [
      'name' => 'feature_1_title',
      'label' => 'Feature 1 - Title',
      'type' => 'text',
      'default' => 'Lightning Fast',
      'description' => 'Title for the first feature card',
    ],
    [
      'name' => 'feature_1_description',
      'label' => 'Feature 1 - Description',
      'type' => 'textarea',
      'default' => 'SSD storage, CDN integration, and optimized servers ensure your website loads in milliseconds.',
      'description' => 'Description for the first feature card',
    ],
    [
      'name' => 'feature_2_title',
      'label' => 'Feature 2 - Title',
      'type' => 'text',
      'default' => 'Bank-Level Security',
      'description' => 'Title for the second feature card',
    ],
    [
      'name' => 'feature_2_description',
      'label' => 'Feature 2 - Description',
      'type' => 'textarea',
      'default' => 'Advanced security measures protect your data with SSL certificates, firewalls, and daily backups.',
      'description' => 'Description for the second feature card',
    ],
    [
      'name' => 'feature_3_title',
      'label' => 'Feature 3 - Title',
      'type' => 'text',
      'default' => 'Expert Support 24/7',
      'description' => 'Title for the third feature card',
    ],
    [
      'name' => 'feature_3_description',
      'label' => 'Feature 3 - Description',
      'type' => 'textarea',
      'default' => 'Our hosting experts are available around the clock to help with any technical issues or questions.',
      'description' => 'Description for the third feature card',
    ],
    [
      'name' => 'feature_4_title',
      'label' => 'Feature 4 - Title',
      'type' => 'text',
      'default' => 'Easily Scalable',
      'description' => 'Title for the fourth feature card',
    ],
    [
      'name' => 'feature_4_description',
      'label' => 'Feature 4 - Description',
      'type' => 'textarea',
      'default' => 'Start small and grow big. Upgrade your resources instantly as your business expands.',
      'description' => 'Description for the fourth feature card',
    ],
    [
      'name' => 'feature_5_title',
      'label' => 'Feature 5 - Title',
      'type' => 'text',
      'default' => 'User-Friendly Control Panel',
      'description' => 'Title for the fifth feature card',
    ],
    [
      'name' => 'feature_5_description',
      'label' => 'Feature 5 - Description',
      'type' => 'textarea',
      'default' => 'Manage your hosting with our intuitive control panel. No technical knowledge required.',
      'description' => 'Description for the fifth feature card',
    ],
    [
      'name' => 'feature_6_title',
      'label' => 'Feature 6 - Title',
      'type' => 'text',
      'default' => '99.9% Uptime Guarantee',
      'description' => 'Title for the sixth feature card',
    ],
    [
      'name' => 'feature_6_description',
      'label' => 'Feature 6 - Description',
      'type' => 'textarea',
      'default' => 'Your website stays online with our reliable infrastructure and uptime monitoring.',
      'description' => 'Description for the sixth feature card',
    ],

    [
      'name' => 'default_theme',
      'label' => 'Default Theme',
      'type' => 'select',
      'options' => [
        'light' => 'Light',
        'dark' => 'Dark',
      ],
      'default' => 'dark',
      'description' => 'Default theme mode when force dark mode is disabled',
    ],

    [
      'name' => 'primary',
      'label' => 'Primary - Brand Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 85%)',
    ],
    [
      'name' => 'secondary',
      'label' => 'Secondary - Brand Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 65%)',
    ],
    [
      'name' => 'neutral',
      'label' => 'Borders, Accents... (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 30%)',
    ],
    [
      'name' => 'base',
      'label' => 'Base - Text Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 0%)',
    ],
    [
      'name' => 'muted',
      'label' => 'Muted - Text Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 40%)',
    ],
    [
      'name' => 'inverted',
      'label' => 'Inverted - Text Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 100%)',
    ],
    [
      'name' => 'background',
      'label' => 'Background - Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 100%)',
    ],
    [
      'name' => 'background-secondary',
      'label' => 'Background - Secondary Color (Light)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 97%)',
    ],

    [
      'name' => 'dark-primary',
      'label' => 'Primary - Brand Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 85%)',
    ],
    [
      'name' => 'dark-secondary',
      'label' => 'Secondary - Brand Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 65%)',
    ],
    [
      'name' => 'dark-neutral',
      'label' => 'Borders, Accents... (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 30%)',
    ],
    [
      'name' => 'dark-base',
      'label' => 'Base - Text Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 100%)',
    ],
    [
      'name' => 'dark-muted',
      'label' => 'Muted - Text Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 70%)',
    ],
    [
      'name' => 'dark-inverted',
      'label' => 'Inverted - Text Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 5%)',
    ],
    [
      'name' => 'dark-background',
      'label' => 'Background - Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 5%)',
    ],
    [
      'name' => 'dark-background-secondary',
      'label' => 'Background - Secondary Color (Dark)',
      'type' => 'color',
      'default' => 'hsl(0, 0%, 10%)',
    ],

    [
      'name' => 'panel_showcase_title',
      'label' => 'Panel Showcase Title',
      'type' => 'text',
      'default' => 'Powerful Game Control Panel',
      'description' => 'Title displayed in the panel showcase section',
    ],
    [
      'name' => 'panel_showcase_description',
      'label' => 'Panel Showcase Description',
      'type' => 'textarea',
      'default' => 'Take full control of your game servers with our intuitive control panel. Easily manage settings, monitor performance, and deploy mods with just a few clicks.',
      'description' => 'Description text displayed in the panel showcase section',
    ],
    [
      'name' => 'panel_showcase_image_url',
      'label' => 'Panel Showcase Image URL',
      'type' => 'text',
      'default' => 'https://placehold.co/1200x800',
      'description' => 'URL to the screenshot of the game control panel (recommended size: 1200x800px)',
    ],

    [
      'name' => 'logo_marquee_title',
      'label' => 'Logo Marquee Title',
      'type' => 'text',
      'default' => 'Trusted by Community Members',
      'description' => 'Title displayed above the logo marquee',
    ],
    [
      'name' => 'logo_marquee_description',
      'label' => 'Logo Marquee Description',
      'type' => 'textarea',
      'default' => 'Join our growing community of industry professionals who rely on our services.',
      'description' => 'Description text displayed below the marquee title',
    ],
    [
      'name' => 'logo_marquee_image_url_1',
      'label' => 'Logo Marquee Image URL 1',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+1',
      'description' => 'URL to partner logo 1 (recommended size: 200x80px)',
    ],
    [
      'name' => 'logo_marquee_image_url_2',
      'label' => 'Logo Marquee Image URL 2',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+2',
      'description' => 'URL to partner logo 2 (recommended size: 200x80px)',
    ],
    [
      'name' => 'logo_marquee_image_url_3',
      'label' => 'Logo Marquee Image URL 3',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+3',
      'description' => 'URL to partner logo 3 (recommended size: 200x80px)',
    ],
    [
      'name' => 'logo_marquee_image_url_4',
      'label' => 'Logo Marquee Image URL 4',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+4',
      'description' => 'URL to partner logo 4 (recommended size: 200x80px)',
    ],
    [
      'name' => 'logo_marquee_image_url_5',
      'label' => 'Logo Marquee Image URL 5',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+5',
      'description' => 'URL to partner logo 5 (recommended size: 200x80px)',
    ],
    [
      'name' => 'logo_marquee_image_url_6',
      'label' => 'Logo Marquee Image URL 6',
      'type' => 'text',
      'default' => 'https://placehold.co/200x80/cccccc/666666?text=Logo+6',
      'description' => 'URL to partner logo 6 (recommended size: 200x80px)',
    ],

    [
      'name' => 'footer_text',
      'label' => 'Footer Description',
      'type' => 'textarea',
      'default' => 'Reliable hosting solutions for businesses of all sizes. Get started in minutes with our easy-to-use platform.',
      'description' => 'Short description text displayed in the footer',
    ],
    [
      'name' => 'footer_cta_text',
      'label' => 'Footer CTA Text',
      'type' => 'text',
      'default' => 'Ready to Get Started?',
      'description' => 'Call to action heading in the footer',
    ],
    [
      'name' => 'footer_cta_description',
      'label' => 'Footer CTA Description',
      'type' => 'textarea',
      'default' => 'Join thousands of satisfied customers who trust us with their hosting needs. Get your website online today!',
      'description' => 'Call to action description text in the footer',
    ],
    [
      'name' => 'cta_primary_text',
      'label' => 'Primary CTA Button Text',
      'type' => 'text',
      'default' => 'Explore Our Services',
      'description' => 'Text for the primary call-to-action button',
    ],
    [
      'name' => 'cta_primary_link',
      'label' => 'Primary CTA Button Link',
      'type' => 'text',
      'default' => '#services',
      'description' => 'Link for the primary call-to-action button (use # for section links or full URLs)',
    ],
    [
      'name' => 'cta_secondary_text',
      'label' => 'Secondary CTA Button Text',
      'type' => 'text',
      'default' => 'Have Questions?',
      'description' => 'Text for the secondary call-to-action button',
    ],
    [
      'name' => 'cta_secondary_link',
      'label' => 'Secondary CTA Button Link',
      'type' => 'text',
      'default' => 'tickets/create',
      'description' => 'Link for the secondary call-to-action button (relative path or full URL)',
    ],

    [
      'name' => 'contact_email',
      'label' => 'Contact Email',
      'type' => 'text',
      'default' => '',
      'description' => 'Email address displayed in the footer (leave empty to use system default)',
    ],
    [
      'name' => 'contact_phone',
      'label' => 'Contact Phone',
      'type' => 'text',
      'default' => '',
      'description' => 'Phone number displayed in the footer (leave empty to use system default)',
    ],
    [
      'name' => 'show_theme_attribution',
      'label' => 'Show Theme Attribution',
      'type' => 'checkbox',
      'default' => true,
      'database_type' => 'boolean',
      'description' => 'Display theme attribution in the footer',
    ],

    [
      'name' => 'social_twitter',
      'label' => 'Twitter/X URL',
      'type' => 'text',
      'default' => '',
      'description' => 'Twitter/X profile URL (leave empty to hide)',
    ],
    [
      'name' => 'social_facebook',
      'label' => 'Facebook URL',
      'type' => 'text',
      'default' => '',
      'description' => 'Facebook page URL (leave empty to hide)',
    ],
    [
      'name' => 'social_instagram',
      'label' => 'Instagram URL',
      'type' => 'text',
      'default' => '',
      'description' => 'Instagram profile URL (leave empty to hide)',
    ],
    [
      'name' => 'social_discord',
      'label' => 'Discord URL',
      'type' => 'text',
      'default' => '',
      'description' => 'Discord server invite URL (leave empty to hide)',
    ]
  ],
];